[package]
name = "rust-crawler"
version = "0.1.0"
authors = ["Kieran Griffiths <griffk04@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.6"
